name: caronapp_front
description: O CaronApp é um aplicativo de carona idealizado pela equipe 9 do Hackathon do Dev. Community destinando para universitários.

publish_to: "none" # Remove this line if you wish to publish to pub.dev

version: 0.1.2+1

environment:
  sdk: ">=2.17.5 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.2
  flutter_spinkit: ^5.1.0

  # Fonte utilizada no projeto KoHo
  google_fonts: ^3.0.1

  # Google maps API
  google_place: ^0.4.7
  google_maps_flutter: ^2.1.8
  flutter_polyline_points: ^1.0.0

  # Launcher image

  multiavatar: ^0.1.5
  flutter_svg: ^1.1.1+1

  mask_text_input_formatter: ^2.3.0
  flutter_rating_bar: ^4.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0
  flutter_launcher_icons: ^0.9.3

flutter_icons:
  image_path: "assets/icons/LauncherCaronAppLogo.png"
  adaptive_icon_background: "assets/icons/LauncherCaronAppLogo_background.png"
  adaptive_icon_foreground: "assets/icons/LauncherCaronAppLogo_foreground.png"
  android: true
  ios: true

flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - assets/icons/

  fonts:
    - family: FE-FONT
      fonts:
        - asset: fonts/FE-FONT.TTF
