import 'package:caronapp_front/pages/motorista/models/motorista/Motorista.dart';

final motoristaList = <Motorista>[
  Motorista(
      "Ariane",
      "Ozú",
      4.8,
      "11989840881",
      DateTime(2002, 10, 4),
      "Engenharia Química",
      "Fox Vermelho",
      "EBN5229",
      "FEMININO",
      2,
      "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Aenean ligula neque, molestie a laoreet vel, viverra vel nisi. Aenean et mattis ex. Maecenas bibendum lacus mollis nisl vulputate euismod. Fusce quis dui scelerisque sapien vestibulum euismod. Praesent ultrices, metus a tristique ultricies, tellus diam ultrices lorem, id vestibulum massa neque ut urna. Morbi dapibus aliquam ipsum eget varius. Maecenas",
      24),
  Motorista(
      "Vitor",
      "Soller",
      5.0,
      "11991758098",
      DateTime(2002, 11, 8),
      "Engenharia da Computação",
      "Corsa 1996 Branco",
      "CET4G97",
      "MASCULINO",
      2,
      "Extrovertido e Divertido",
      15),
  Motorista(
      "Lucas",
      "Milani",
      4.8,
      "11989173614",
      DateTime(2003, 6, 10),
      "Engenharia da Computação",
      "Meriva 2014 Preto",
      "DHD4278",
      "MASCULINO",
      1,
      "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Aenean ligula neque, molestie a laoreet vel, viverra vel nisi. Aenean et mattis ex. Maecenas bibendum lacus mollis nisl vulputate euismod. Fusce quis dui scelerisque sapien vestibulum euismod. Praesent ultrices, metus a tristique ultricies, tellus diam ultrices lorem, id vestibulum massa neque ut urna. Morbi dapibus aliquam ipsum eget varius. Maecenas",
      16),
  Motorista(
      "Luigi",
      "Trevisan",
      4.1,
      "11981643251",
      DateTime(2003, 17, 12),
      "Ciência da Computação",
      "Porsche Panamera Verde",
      "SOF1805",
      "MASCULINO",
      1,
      "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Aenean ligula neque, molestie a laoreet vel, viverra vel nisi. Aenean et mattis ex. Maecenas bibendum lacus mollis nisl vulputate euismod. Fusce quis dui scelerisque sapien vestibulum euismod. Praesent ultrices, metus a tristique ultricies, tellus diam ultrices lorem, id vestibulum massa neque ut urna. Morbi dapibus aliquam ipsum eget varius. Maecenas",
      24),
  Motorista(
      "Felipe",
      "Ariel",
      2.0,
      "11941573688",
      DateTime(2004, 1, 1),
      "Ciência da Computação",
      "Fusca 1974 Preto",
      "HOX8703",
      "MASCULINO",
      1,
      "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Aenean ligula neque, molestie a laoreet vel, viverra vel nisi. Aenean et mattis ex. Maecenas bibendum lacus mollis nisl vulputate euismod. Fusce quis dui scelerisque sapien vestibulum euismod. Praesent ultrices, metus a tristique ultricies, tellus diam ultrices lorem, id vestibulum massa neque ut urna. Morbi dapibus aliquam ipsum eget varius. Maecenas",
      1),
  Motorista(
      "Cláudia Pietra",
      "Mariana Jesus",
      4.5,
      "11988173860",
      DateTime(1999, 3, 17),
      "Engenharia de Alimentos",
      "Ford Ka Branco",
      "JTL1752",
      "FEMININO",
      4,
      "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Aenean ligula neque, molestie a laoreet vel, viverra vel nisi. Aenean et mattis ex. Maecenas bibendum lacus mollis nisl vulputate euismod. Fusce quis dui scelerisque sapien vestibulum euismod. Praesent ultrices, metus a tristique ultricies, tellus diam ultrices lorem, id vestibulum massa neque ut urna. Morbi dapibus aliquam ipsum eget varius. Maecenas",
      10),
  Motorista(
      "Henrique Felipe",
      "Monteiro",
      4.8,
      "11997353110",
      DateTime(2000, 7, 20),
      "Engenharia Mecânica",
      "HB20 Prata",
      "GLJ0789",
      "MASCULINO",
      3,
      "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Aenean ligula neque, molestie a laoreet vel, viverra vel nisi. Aenean et mattis ex. Maecenas bibendum lacus mollis nisl vulputate euismod. Fusce quis dui scelerisque sapien vestibulum euismod. Praesent ultrices, metus a tristique ultricies, tellus diam ultrices lorem, id vestibulum massa neque ut urna. Morbi dapibus aliquam ipsum eget varius. Maecenas",
      9),
  Motorista(
      "Vitor Marcos",
      "Vinicius Igor Assunção",
      4.9,
      "11992090620",
      DateTime(1999, 08, 1),
      "Engenharia Química",
      "HB20 Vermelha",
      "LHO2J16",
      "MASCULINO",
      5,
      "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Aenean ligula neque, molestie a laoreet vel, viverra vel nisi. Aenean et mattis ex. Maecenas bibendum lacus mollis nisl vulputate euismod. Fusce quis dui scelerisque sapien vestibulum euismod. Praesent ultrices, metus a tristique ultricies, tellus diam ultrices lorem, id vestibulum massa neque ut urna. Morbi dapibus aliquam ipsum eget varius. Maecenas",
      15),
  Motorista(
      "Renato Anderson",
      "Almeida",
      4.3,
      "11992090620",
      DateTime(1999, 06, 25),
      "Engenharia de Produção",
      "HB20 Rosa",
      "JZC8972",
      "MASCULINO",
      3,
      "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Aenean ligula neque, molestie a laoreet vel, viverra vel nisi. Aenean et mattis ex. Maecenas bibendum lacus mollis nisl vulputate euismod. Fusce quis dui scelerisque sapien vestibulum euismod. Praesent ultrices, metus a tristique ultricies, tellus diam ultrices lorem, id vestibulum massa neque ut urna. Morbi dapibus aliquam ipsum eget varius. Maecenas",
      24),
  Motorista(
      "José",
      "Alfredo Fernades",
      4.3,
      "11992090620",
      DateTime(2002, 11, 2),
      "Engenharia Civil",
      "Toro 2012 Branca",
      "MQU2263",
      "MASCULINO",
      2,
      "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Aenean ligula neque, molestie a laoreet vel, viverra vel nisi. Aenean et mattis ex. Maecenas bibendum lacus mollis nisl vulputate euismod. Fusce quis dui scelerisque sapien vestibulum euismod. Praesent ultrices, metus a tristique ultricies, tellus diam ultrices lorem, id vestibulum massa neque ut urna. Morbi dapibus aliquam ipsum eget varius. Maecenas",
      25),
];
